services:
  web:
    build: .
    image: home-secret:web
    expose:
      - "3000"
    environment:
      NODE_ENV: production
    command: npm run start
    networks:
      - aivia_net

  nginx:
    image: nginx:alpine
    container_name: home-secret-nginx
    depends_on:
      - web
    expose:
      - "80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - aivia_net

networks:
  aivia_net:
    external: true
